channels:
  - anaconda
  - plotly
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - asttokens=2.4.1
  - backcall=0.2.0
  - blas=1.0
  - blessed=1.20.0
  - bottleneck=1.3.7
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2024.12.31
  - certifi=2024.8.30
  - cffi=1.15.1
  - comm=0.1.4
  - contourpy=1.0.5
  - cryptography=41.0.3
  - cuda-cudart=11.7.99
  - cuda-cupti=11.7.101
  - cuda-libraries=11.7.1
  - cuda-nvrtc=11.7.99
  - cuda-nvtx=11.7.91
  - cuda-runtime=11.7.1
  - cudatoolkit=11.0.221
  - cycler=0.11.0
  - cyrus-sasl=2.1.28
  - dbus=1.13.18
  - debugpy=1.6.7
  - decorator=5.1.1
  - entrypoints=0.4
  - executing=2.0.1
  - expat=2.5.0
  - ffmpeg=4.3
  - filelock=3.13.1
  - fontconfig=2.14.1
  - fonttools=4.25.0
  - freetype=2.12.1
  - giflib=5.2.1
  - glib=2.69.1
  - gmp=6.2.1
  - gmpy2=2.1.2
  - gnutls=3.6.15
  - gpustat=1.1.1
  - gst-plugins-base=1.14.1
  - gstreamer=1.14.1
  - h5py=3.9.0
  - hdf5=1.12.1
  - icu=73.1
  - importlib_metadata=7.0.1
  - importlib_resources=6.1.1
  - intel-openmp=2021.4.0
  - ipykernel=6.26.0
  - ipython=8.12.0
  - jedi=0.19.1
  - jinja2=3.1.2
  - jpeg=9e
  - jupyter_client=8.6.0
  - jupyter_core=5.6.0
  - kiwisolver=1.4.4
  - krb5=1.20.1
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libclang=14.0.6
  - libclang13=14.0.6
  - libcublas=11.10.3.66
  - libcufft=10.7.2.124
  - libcufile=1.8.1.2
  - libcups=2.4.2
  - libcurand=10.3.4.101
  - libcurl=8.2.1
  - libcusolver=11.4.0.1
  - libcusparse=11.7.4.91
  - libdeflate=1.17
  - libedit=3.1.20230828
  - libev=4.33
  - libffi=3.3
  - libgcc-ng=11.2.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libgomp=11.2.0
  - libiconv=1.16
  - libidn2=2.3.4
  - liblapack=3.9.0
  - libllvm14=14.0.6
  - libnghttp2=1.52.0
  - libnpp=11.7.4.75
  - libnvjpeg=11.8.0.2
  - libpng=1.6.39
  - libpq=12.15
  - libsodium=1.0.18
  - libssh2=1.10.0
  - libstdcxx-ng=11.2.0
  - libtasn1=4.19.0
  - libtiff=4.5.1
  - libunistring=0.9.10
  - libuuid=1.41.5
  - libuv=1.44.2
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - libxcb=1.15
  - libxkbcommon=1.0.1
  - libxml2=2.10.4
  - lz4-c=1.9.4
  - matplotlib=3.7.2
  - matplotlib-base=3.7.2
  - matplotlib-inline=0.1.6
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - mpc=1.1.0
  - mpfr=4.0.2
  - mpi=1.0
  - mpmath=1.3.0
  - munkres=1.1.4
  - mysql=5.7.24
  - ncurses=6.4
  - nest-asyncio=1.5.8
  - nettle=3.7.3
  - networkx=3.1
  - ninja=1.10.2
  - ninja-base=1.10.2
  - numexpr=2.8.4
  - numpy-base=1.24.3
  - nvidia-ml-py=12.535.133
  - openh264=2.1.1
  - openjpeg=2.4.0
  - openmpi=4.1.6
  - openssl=1.1.1w
  - pandas=2.0.3
  - parso=0.8.3
  - pcre=8.45
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=10.0.1
  - platformdirs=4.1.0
  - plotly=5.24.1
  - ply=3.11
  - pooch=1.7.0
  - prompt-toolkit=3.0.42
  - prompt_toolkit=3.0.42
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pycparser=2.21
  - pygments=2.17.2
  - pyopenssl=23.2.0
  - pyparsing=3.0.9
  - pyqt=5.15.10
  - pyqt5-sip=12.13.0
  - pysocks=1.7.1
  - python=3.8.5
  - python-dateutil=2.8.2
  - python-spams=2.6.1
  - python-tzdata=2023.3
  - python_abi=3.8
  - pytorch=2.0.1
  - pytorch-cuda=11.7
  - pytorch-mutex=1.0
  - pytorch-warmup=0.2.0
  - pytorch_warmup=0.2.0
  - pytz=2023.3.post1
  - pyzmq=25.1.0
  - qt-main=5.15.2
  - readline=8.2
  - scikit-learn=1.3.0
  - seaborn=0.12.2
  - setuptools=68.2.2
  - sip=6.7.12
  - six=1.16.0
  - sqlite=3.41.2
  - stack_data=0.6.2
  - sympy=1.12
  - threadpoolctl=2.2.0
  - tk=8.6.12
  - tomli=2.0.1
  - torchaudio=2.0.2
  - torchtriton=2.0.0
  - torchvision=0.15.2
  - tornado=6.4.1
  - traitlets=5.14.0
  - typing_extensions=4.7.1
  - wcwidth=0.2.12
  - wheel=0.41.2
  - xz=5.4.5
  - zeromq=4.3.4
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
    - absl-py==2.0.0
    - aiohttp==3.9.1
    - aiosignal==1.3.1
    - alabaster==0.7.13
    - albumentations==1.3.1
    - altair==5.2.0
    - annotated-types==0.7.0
    - antlr4-python3-runtime==4.8
    - anyio==4.5.2
    - appdirs==1.4.4
    - asciitree==0.3.3
    - async-lru==2.0.4
    - async-timeout==4.0.3
    - attrs==23.1.0
    - awscli==1.37.25
    - babel==2.16.0
    - backports-zoneinfo==0.2.1
    - beautifulsoup4==4.12.3
    - blinker==1.7.0
    - blis==0.7.11
    - blobfile==3.0.0
    - bokeh==3.1.1
    - botocore==1.36.25
    - cachetools==5.3.2
    - catalogue==2.0.10
    - chardet==5.2.0
    - charset-normalizer==3.3.2
    - clean-fid==0.1.35
    - click==8.1.7
    - cloudpathlib==0.20.0
    - colorama==0.4.6
    - concurrentbuffer==0.0.8
    - confection==0.1.5
    - conllu==6.0.0
    - cymem==2.0.8
    - datasets==2.20.0
    - dicfg==0.0.13
    - dicomweb-client==0.59.3
    - dill==0.3.8
    - docker-pycreds==0.4.0
    - docutils==0.16
    - einops==0.8.1
    - einops-exts==0.0.4
    - et-xmlfile==1.1.0
    - exceptiongroup==1.2.2
    - fasteners==0.19
    - fastjsonschema==2.20.0
    - flask==3.0.0
    - flask-cors==4.0.0
    - flatbuffers==25.2.10
    - frozenlist==1.4.1
    - fsspec==2023.12.2
    - ftfy==6.1.3
    - future==0.18.3
    - gitdb==4.0.11
    - gitpython==3.1.40
    - glymur==0.12.8
    - google-auth==2.25.2
    - google-auth-oauthlib==1.0.0
    - grpcio==1.60.0
    - huggingface-hub==0.24.5
    - humanize==4.10.0
    - idna==3.6
    - imagecodecs==2023.3.16
    - imageio==2.9.0
    - imageio-ffmpeg==0.4.2
    - imagesize==1.4.1
    - imgaug==0.2.6
    - importlib==1.0.4
    - importlib-metadata==6.11.0
    - ipywidgets==8.1.2
    - itsdangerous==2.2.0
    - jax==0.4.13
    - jaxlib==0.4.13
    - jmespath==1.0.1
    - joblib==1.3.2
    - json5==0.9.25
    - jsonschema==4.20.0
    - jsonschema-specifications==2023.11.2
    - jupyter-client==8.6.3
    - jupyter-events==0.10.0
    - jupyter-lsp==2.2.5
    - jupyter-server==2.14.2
    - jupyterlab==4.0.9
    - jupyterlab-server==2.27.3
    - jupyterlab-widgets==3.0.10
    - kornia==0.7.3
    - kornia-rs==0.1.7
    - langcodes==3.4.1
    - language-data==1.2.0
    - lazy-loader==0.3
    - lightning-utilities==0.10.0
    - llvmlite==0.41.1
    - lpips==0.1.4
    - lxml==5.3.0
    - marisa-trie==1.2.1
    - markdown==3.5.1
    - markdown-it-py==3.0.0
    - markupsafe==2.1.3
    - mdurl==0.1.2
    - mediapipe==0.10.11
    - mistune==3.0.2
    - ml-dtypes==0.2.0
    - mpi4py==4.0.0
    - multidict==6.0.4
    - multiprocess==0.70.16
    - murmurhash==1.0.10
    - nbclient==0.10.0
    - nbconvert==7.16.4
    - nbformat==5.10.4
    - nmslib==2.1.1
    - notebook-shim==0.2.4
    - numba==0.58.1
    - numcodecs==0.12.1
    - numpy==1.24.4
    - nvidia-cublas-cu12==12.1.3.1
    - nvidia-cuda-cupti-cu12==12.1.105
    - nvidia-cuda-nvrtc-cu12==12.1.105
    - nvidia-cuda-runtime-cu12==12.1.105
    - nvidia-cudnn-cu12==8.9.2.26
    - nvidia-cufft-cu12==11.0.2.54
    - nvidia-curand-cu12==10.3.2.106
    - nvidia-cusolver-cu12==11.4.5.107
    - nvidia-cusparse-cu12==12.1.0.106
    - nvidia-nccl-cu12==2.18.1
    - nvidia-nvjitlink-cu12==12.3.101
    - nvidia-nvtx-cu12==12.1.105
    - oauthlib==3.2.2
    - omegaconf==2.1.1
    - open-clip-torch==2.23.0
    - opencv-contrib-python==4.11.0.86
    - opencv-python==4.8.0.76
    - opencv-python-headless==4.8.1.78
    - openpyxl==3.1.5
    - openslide-python==1.3.1
    - opt-einsum==3.4.0
    - overrides==7.7.0
    - packaging==24.2
    - pip==24.3.1
    - pipdeptree==2.24.0
    - pkgutil-resolve-name==1.3.10
    - preshed==3.0.9
    - prometheus-client==0.21.0
    - protobuf==3.20.1
    - pudb==2019.2
    - pyarrow==17.0.0
    - pyarrow-hotfix==0.6
    - pyasn1==0.5.1
    - pyasn1-modules==0.3.0
    - pybind11==2.6.1
    - pycocotools==2.0.7
    - pycryptodomex==3.21.0
    - pydantic==2.9.2
    - pydantic-core==2.23.4
    - pydeck==0.8.1b0
    - pydeprecate==0.3.1
    - pydicom==2.4.4
    - pynndescent==0.5.13
    - pysbd==0.3.4
    - python-json-logger==2.0.7
    - pytorch-fid==0.3.0
    - pytorch-lightning==1.4.2
    - pywavelets==1.4.1
    - pyyaml==6.0.1
    - qudida==0.0.4
    - referencing==0.32.0
    - regex==2023.12.25
    - requests==2.31.0
    - requests-oauthlib==1.3.1
    - retrying==1.3.4
    - rich==13.7.0
    - rpds-py==0.15.2
    - rsa==4.7.2
    - rtree==1.3.0
    - s3transfer==0.11.2
    - sacremoses==0.1.1
    - safetensors==0.4.1
    - scikit-image==0.20.0
    - scipy==1.9.1
    - scispacy==0.5.4
    - send2trash==1.8.3
    - sentence-transformers==3.1.1
    - sentencepiece==0.1.99
    - sentry-sdk==1.39.1
    - setproctitle==1.3.3
    - shapely==2.0.2
    - shellingham==1.5.4
    - simpleitk==2.3.1
    - smart-open==7.0.5
    - smmap==5.0.1
    - snowballstemmer==2.2.0
    - sounddevice==0.5.1
    - soupsieve==2.6
    - sourcelib==0.0.4
    - spacy==3.7.5
    - spacy-legacy==3.0.12
    - spacy-loggers==1.0.5
    - sphinx==7.1.2
    - sphinxcontrib-applehelp==1.0.4
    - sphinxcontrib-devhelp==1.0.2
    - sphinxcontrib-htmlhelp==2.0.1
    - sphinxcontrib-jsmath==1.0.1
    - sphinxcontrib-qthelp==1.0.3
    - sphinxcontrib-serializinghtml==1.1.5
    - srsly==2.4.8
    - staintools==2.1.2
    - streamlit==1.29.0
    - tenacity==8.2.3
    - tensorboard==2.14.0
    - tensorboard-data-server==0.7.2
    - test-tube==0.7.5
    - thinc==8.2.5
    - tiatoolbox==1.5.1
    - tifffile==2023.7.10
    - timm==0.9.12
    - tokenizers==0.20.3
    - toml==0.10.2
    - toolz==0.12.0
    - torch==2.0.1
    - torch-fidelity==0.3.0
    - torchmetrics==0.7.0
    - tqdm==4.66.3
    - transformers==4.46.3
    - triton==2.1.0
    - typer==0.12.5
    - tzlocal==5.2
    - umap-learn==0.5.5
    - urllib3==2.1.0
    - urwid==2.3.4
    - validators==0.22.0
    - wandb==0.16.1
    - wasabi==1.1.3
    - watchdog==3.0.0
    - weasel==0.4.1
    - webcolors==24.8.0
    - websocket-client==1.8.0
    - werkzeug==3.0.1
    - wget==3.2
    - wholeslidedata==0.1.0
    - widgetsnbextension==4.0.10
    - wrapt==1.16.0
    - wsidicom==0.13.0
    - xxhash==3.4.1
    - xyzservices==2024.9.0
    - yarl==1.9.4
    - zarr==2.16.1
    - zenodo-get==1.6.1
    - zipp==3.17.0
