model:
  base_learning_rate: 2.5e-05
  target: ldm.models.diffusion.ddpm.LatentDiffusion
  params:
    linear_start: 0.0015
    linear_end: 0.0195
    num_timesteps_cond: 1
    log_every_t: 200 # 200 reduce this to reduce the logging time
    timesteps: 1000 # 1000 reduce this to reduce the debugging time
    first_stage_key: image
    cond_stage_key: caption_mask
    image_size: 64
    channels: 3
    cond_stage_trainable: True
    conditioning_key: crossattn_add
    monitor: val/loss
    use_ema: false
    fid_path: /a2il/data/mbhosale/PathDiff/PanNuke/validation_fid_stats.npz
    scheduler_config:
      target: ldm.lr_scheduler.LambdaLinearScheduler
      params:
        warm_up_steps:
        - 1000
        cycle_lengths:
        - 10000000000000
        f_start:
        - 1.0e-06
        f_max:
        - 1.0
        f_min:
        - 1.0
    unet_config:
      target: ldm.modules.diffusionmodules.openaimodel.UNetModel
      params:
        image_size: 64
        in_channels: 3
        out_channels: 3
        model_channels: 192
        attention_resolutions:
        - 8
        - 4
        - 2
        num_res_blocks: 2
        channel_mult:
        - 1
        - 2
        - 3
        - 5
        num_heads: 1
        use_spatial_transformer: true
        transformer_depth: 1
        context_dim: 512
        ckpt_path: models/ldm/cin256-v2/unet.ckpt
    first_stage_config:
      target: ldm.models.autoencoder.VQModelInterface
      params:
        ckpt_path: models/first_stage_models/vq-f4-tcga-brca/last.ckpt
        embed_dim: 3
        n_embed: 8192
        ddconfig:
          double_z: false
          z_channels: 3
          resolution: 256
          in_channels: 3
          out_ch: 3
          ch: 128
          ch_mult:
          - 1
          - 2
          - 4
          num_res_blocks: 2
          attn_resolutions: []
          dropout: 0.0
        lossconfig:
          target: torch.nn.Identity
    cond_stage_config:
      target: ldm.modules.encoders.modules.MaskEmbedder
      params:
        conditional_channels: 3
        out_channels: [16, 64, 256]
      secondary_cond_stage_config:
        secondary_cond_stage_trainable: false
        target: ldm.modules.encoders.modules.FrozenCLIPEmbedder
        params:
          version: vinid/plip
          max_length: 154
data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 64
    num_workers: 12
    wrap: false
    train:
      target: ldm.data.mask_cond.mask_condition.PanNukeDatasetV2
      params:
        config:
          root: /data_local1/mbhosale/PathDiff/PanNuke/PanNuke2
          split: train
          # crop_size: 256 # Crop size not needed, since size is already 256, quite small.
          num_levels: 2
          p_uncond: 0.1
          inference: True
    validation:
      target: ldm.data.mask_cond.mask_condition.PanNukeDatasetV2
      params:
        config:
          root: /data_local1/mbhosale/PathDiff/PanNuke/PanNuke2
          split: test
          # crop_size: 256
          num_levels: 2
          p_uncond: 0.1
          inference: True

lightning:
  callbacks:
    image_logger:
      target: main.ImageLogger
      params:
        batch_frequency: 2000 # 5000 reduce this to reduce the logging time / checkpointing time
        max_images: 8
        increase_log_steps: false
        log_images_kwargs:
          quantize_denoised: false
          inpaint: false
    model_checkpoint:
      target: pytorch_lightning.callbacks.ModelCheckpoint
      params:
        save_weights_only: true
  trainer:
    benchmark: true
    accelerator: ddp
    gpus: 0, 1, 3, 4